- name: "Create Newsboat and Podboat config dirs"
  ansible.builtin.include_tasks: create_dirs.yml

- name: "Configure main Newsboat and Podboat settings"
  ansible.builtin.include_tasks: settings.yml

- name: "Try to set up a link to existing user RSS-tracking database file"
  ansible.builtin.include_tasks: rss_tracking_db.yml

